name: homeqartapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  expandable: ^5.0.1
  pin_code_text_field: ^1.8.0
  animated_flip_counter: ^0.2.1
  get: ^4.6.1
  get_storage: ^2.0.3
  http: ^0.13.4
  dio: ^4.0.4
  webview_flutter: ^2.1.2
  shimmer: ^2.0.0
  url_launcher: ^6.0.17
  fluttertoast: ^8.0.8
  carousel_slider: ^4.0.0
  image_picker: ^0.8.4+4
  share_plus: ^3.0.4
  flutter_svg: ^1.0.0
  flutter_rating_bar: ^4.0.0
  universal_html: ^2.0.8
  future_progress_dialog: ^0.2.0
  cached_network_image: ^3.2.0
  flutter_datetime_picker: ^1.5.1
  intl: ^0.17.0
  flutter_html: 
  flutter_launcher_icons: ^0.9.2
  launch_review: ^3.0.1
  
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter

    
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/

  fonts:
       - family: InterRegular
         fonts:
           - asset: assets/fonts/Inter-Regular.ttf

       - family: InterMedium
         fonts:
           - asset: assets/fonts/Inter-Medium.ttf

       - family: InterBold
         fonts:
           - asset: assets/fonts/Inter-Bold.ttf

       - family: InterExtraBold
         fonts:
           - asset: assets/fonts/Inter-ExtraBold.ttf